import { FC, useState, useMemo, useEffect } from 'react';
import { CalendarIcon, Loader2, CheckCircle, XCircle, AlertCircle, Clock, Info } from 'lucide-react';
import pepeIcon from '@/assets/pepe-icon.png';
import { ModuleCard } from './ModuleCard';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { FeeDisplay } from './FeeDisplay';
import { useWallet } from '@solana/wallet-adapter-react';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';
import { fetchMemeData, formatPrice, formatMarketCap, MemeTokenData } from '@/utils/apiService';
import { toast } from '@/hooks/use-toast';
import { DeploymentState } from '@/hooks/useCreateFeed';
import { 
  getDefaultLocalResolutionDate, 
  getDefaultLocalHour, 
  getDefaultLocalMinute, 
  createDateTimeFromLocal, 
  formatDateTimeForTitle,
  formatLocalDateTime,
  isValidFutureTime,
  getTimezoneAbbr
} from '@/utils/utcTime';

type MetricType = 'price' | 'marketcap';

const MIN_MARKET_CAP = 1_000_000; // $1M minimum

interface MemecoinModuleProps {
  onCreateFeed: (config: { 
    contractAddress: string; 
    title: string; 
    metric: MetricType;
    resolutionDate: Date;
    tokenLogo?: string;
  }) => void;
  isLoading?: boolean;
  deploymentState?: DeploymentState;
  getButtonText?: (defaultText?: string) => string;
}

export const MemecoinModule: FC<MemecoinModuleProps> = ({ onCreateFeed, isLoading, deploymentState, getButtonText }) => {
  const { connected } = useWallet();
  const [contractAddress, setContractAddress] = useState('');
  const [metric, setMetric] = useState<MetricType>('price');
  
  // Initialize with smart local defaults (displayed as local, stored as UTC)
  const defaultDate = getDefaultLocalResolutionDate();
  const [resolutionDate, setResolutionDate] = useState<Date>(defaultDate);
  const [selectedHour, setSelectedHour] = useState<string>(getDefaultLocalHour(defaultDate));
  const [selectedMinute, setSelectedMinute] = useState<string>(getDefaultLocalMinute(defaultDate));
  const tzAbbr = getTimezoneAbbr();
  
  // Live preview state
  const [tokenData, setTokenData] = useState<MemeTokenData | null>(null);
  const [isFetching, setIsFetching] = useState(false);
  const [fetchError, setFetchError] = useState(false);

  const isValidAddress = contractAddress.length >= 32 && contractAddress.length <= 44;

  // Calculate full resolution datetime (local input -> Date object with correct UTC)
  const fullResolutionDate = useMemo(() => {
    if (!resolutionDate) return undefined;
    return createDateTimeFromLocal(resolutionDate, selectedHour, selectedMinute);
  }, [resolutionDate, selectedHour, selectedMinute]);

  // Validate minimum 1 hour in future (UTC)
  const isValidTime = fullResolutionDate ? isValidFutureTime(fullResolutionDate) : true;

  // Check market cap validation
  const isMarketCapValid = tokenData ? parseFloat(String(tokenData.marketCap)) >= MIN_MARKET_CAP : true;

  // Fetch token data when address changes
  useEffect(() => {
    const fetchData = async () => {
      if (!isValidAddress) {
        setTokenData(null);
        setFetchError(false);
        return;
      }

      setIsFetching(true);
      setFetchError(false);

      try {
        const data = await fetchMemeData(contractAddress);
        if (data) {
          setTokenData(data);
          setFetchError(false);
        } else {
          setTokenData(null);
          setFetchError(true);
        }
      } catch (error) {
        setTokenData(null);
        setFetchError(true);
        toast({
          title: "Failed to fetch data",
          description: "Could not retrieve token data from GeckoTerminal",
          variant: "destructive",
        });
      } finally {
        setIsFetching(false);
      }
    };

    const debounceTimer = setTimeout(fetchData, 500);
    return () => clearTimeout(debounceTimer);
  }, [contractAddress, isValidAddress]);

  // Auto-generate feed title (shows UTC in title for global consistency)
  const autoGeneratedTitle = useMemo(() => {
    if (!fullResolutionDate) return '';
    const symbol = tokenData?.symbol || contractAddress.slice(0, 4).toUpperCase();
    const metricLabel = metric === 'price' ? 'Price' : 'Market Cap';
    const dateLabel = formatDateTimeForTitle(fullResolutionDate);
    return `${symbol} ${metricLabel} [${dateLabel}]`;
  }, [contractAddress, tokenData, metric, fullResolutionDate]);

  const handleCreate = () => {
    if (!contractAddress.trim() || !fullResolutionDate) return;
    onCreateFeed({
      contractAddress: contractAddress.trim(),
      title: autoGeneratedTitle,
      metric,
      resolutionDate: fullResolutionDate,
      tokenLogo: tokenData?.imageUrl,
    });
  };

  const canCreate = connected && isValidAddress && fullResolutionDate && tokenData && isValidTime && isMarketCapValid;

  return (
    <ModuleCard
      iconImage={pepeIcon}
      title="Memecoins"
      description="Comprehensive tracking for the Solana memecoins"
      index={1}
    >
      <div className="space-y-4 flex-1 flex flex-col">
        {/* Token Address */}
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <Label className="text-sm font-medium text-foreground">Token Address</Label>
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Info className="h-4 w-4 text-muted-foreground cursor-help" />
                </TooltipTrigger>
                <TooltipContent className="max-w-[250px]">
                  <p>Only tokens with &gt;$1M Market Cap are allowed to ensure liquidity and accurate data.</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
          <Input
            placeholder="Paste contract address..."
            value={contractAddress}
            onChange={(e) => setContractAddress(e.target.value)}
            className="bg-background border-border font-mono text-sm w-full max-w-full overflow-hidden"
          />
          
          {/* Live Preview */}
          {isFetching && (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="h-3 w-3 animate-spin" />
              <span>Fetching token data...</span>
            </div>
          )}
          
          {tokenData && !isFetching && isMarketCapValid && (
            <div className="flex items-start gap-3 p-3 bg-green-500/10 border border-green-500/20 rounded-md">
              {/* Token Image */}
              {tokenData.imageUrl && (
                <img 
                  src={tokenData.imageUrl} 
                  alt={tokenData.symbol}
                  className="w-10 h-10 rounded-full shrink-0 border border-green-500/30"
                  onError={(e) => { e.currentTarget.style.display = 'none'; }}
                />
              )}
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500 shrink-0" />
                  <span className="text-green-600 font-medium">Token Found: {tokenData.symbol}</span>
                </div>
                <div className="text-sm mt-1 text-foreground">
                  <span>Price: ${formatPrice(tokenData.priceUsd)}</span>
                  <span className="text-muted-foreground mx-2">|</span>
                  <span>MC: {formatMarketCap(tokenData.marketCap)}</span>
                </div>
              </div>
            </div>
          )}

          {/* Market Cap Too Low Error */}
          {tokenData && !isFetching && !isMarketCapValid && (
            <div className="flex items-start gap-3 p-3 bg-destructive/10 border border-destructive/20 rounded-md">
              {tokenData.imageUrl && (
                <img 
                  src={tokenData.imageUrl} 
                  alt={tokenData.symbol}
                  className="w-10 h-10 rounded-full shrink-0 border border-destructive/30 opacity-50"
                  onError={(e) => { e.currentTarget.style.display = 'none'; }}
                />
              )}
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <AlertCircle className="h-4 w-4 text-destructive shrink-0" />
                  <span className="text-destructive font-medium">Market Cap Too Low</span>
                </div>
                <div className="text-sm mt-1">
                  <span className="text-muted-foreground">{tokenData.symbol}</span>
                  <span className="text-muted-foreground mx-2">|</span>
                  <span className="text-muted-foreground">MC: {formatMarketCap(tokenData.marketCap)}</span>
                </div>
                <p className="text-xs text-destructive mt-2">
                  Market Cap is below $1M. Too risky for an oracle.
                </p>
              </div>
            </div>
          )}
          
          {fetchError && !isFetching && isValidAddress && (
            <div className="flex items-center gap-2 p-2 bg-destructive/10 border border-destructive/20 rounded-md">
              <XCircle className="h-4 w-4 text-destructive shrink-0" />
              <span className="text-sm text-destructive">Token not found on Solana</span>
            </div>
          )}
          
          {contractAddress && !isValidAddress && (
            <p className="text-xs text-destructive">Invalid address length</p>
          )}
        </div>

        {/* Metric Selector - Segmented Control */}
        <div className="space-y-2">
          <Label className="text-sm font-medium text-foreground">Metric to Track</Label>
          <div className="flex bg-muted rounded-lg p-1">
            <button
              type="button"
              onClick={() => setMetric('price')}
              className={cn(
                "flex-1 py-2 px-3 text-sm font-medium rounded-md transition-all duration-200",
                metric === 'price'
                  ? "bg-primary text-primary-foreground shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              )}
            >
              Price ($)
            </button>
            <button
              type="button"
              onClick={() => setMetric('marketcap')}
              className={cn(
                "flex-1 py-2 px-3 text-sm font-medium rounded-md transition-all duration-200",
                metric === 'marketcap'
                  ? "bg-primary text-primary-foreground shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              )}
            >
              Market Cap
            </button>
          </div>
        </div>

        {/* Resolution Date & Time (Local) */}
        <div className="space-y-2">
          <Label className="text-sm font-medium text-foreground">
            Resolution Date & Time <span className="text-muted-foreground text-xs">({tzAbbr})</span>
          </Label>
          <div className="flex flex-wrap gap-2">
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className={cn(
                    "flex-1 min-w-[140px] justify-start text-left font-normal bg-background border-border",
                    !resolutionDate && "text-muted-foreground"
                  )}
                >
                  <CalendarIcon className="mr-2 h-4 w-4 shrink-0" />
                  <span className="truncate">{resolutionDate ? format(resolutionDate, "PPP") : "Select date"}</span>
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0 bg-popover border-border z-50" align="start" collisionPadding={16}>
                <Calendar
                  mode="single"
                  selected={resolutionDate}
                  onSelect={setResolutionDate}
                  disabled={(date) => date < new Date()}
                  initialFocus
                  className="p-3 pointer-events-auto"
                />
              </PopoverContent>
            </Popover>
            
            {/* Time Selection */}
            <div className="flex items-center gap-1">
              <Clock className="h-4 w-4 text-muted-foreground" />
              <Input
                type="text"
                inputMode="numeric"
                maxLength={2}
                value={selectedHour}
                onChange={(e) => {
                  const val = e.target.value.replace(/\D/g, '').slice(0, 2);
                  setSelectedHour(val);
                }}
                onBlur={(e) => {
                  let val = parseInt(e.target.value) || 0;
                  val = Math.min(23, Math.max(0, val));
                  setSelectedHour(val.toString().padStart(2, '0'));
                }}
                className="w-14 bg-background border-border text-center"
                placeholder="HH"
              />
              <span className="text-muted-foreground font-medium">:</span>
              <Input
                type="text"
                inputMode="numeric"
                maxLength={2}
                value={selectedMinute}
                onChange={(e) => {
                  const val = e.target.value.replace(/\D/g, '').slice(0, 2);
                  setSelectedMinute(val);
                }}
                onBlur={(e) => {
                  let val = parseInt(e.target.value) || 0;
                  val = Math.min(59, Math.max(0, val));
                  setSelectedMinute(val.toString().padStart(2, '0'));
                }}
                className="w-14 bg-background border-border text-center"
                placeholder="MM"
              />
            </div>
          </div>
          
          {/* Time Validation Error */}
          {fullResolutionDate && !isValidTime && (
            <p className="text-xs text-destructive flex items-center gap-1">
              <XCircle className="h-3 w-3" />
              Minimum duration is 2 minutes from now
            </p>
          )}
        </div>

        {/* Auto-generated Feed Title Preview */}
        {autoGeneratedTitle && (
          <div className="space-y-2">
            <Label className="text-sm font-medium text-muted-foreground">Feed Title (auto)</Label>
            <div className="px-3 py-2 bg-muted/50 rounded-md border border-border/50 h-10 flex items-center">
              <span className="text-sm text-foreground truncate">{autoGeneratedTitle}</span>
            </div>
          </div>
        )}
        
        {/* Spacer to push button to bottom */}
        <div className="flex-1" />

        <div className="flex items-center justify-between pt-2">
          <FeeDisplay />
          <Button
            variant={deploymentState === 'success' ? 'default' : 'gold'}
            size="sm"
            onClick={handleCreate}
            disabled={!canCreate || isLoading}
            className={deploymentState === 'success' ? 'bg-green-500 hover:bg-green-600' : ''}
          >
            {getButtonText ? getButtonText('Create Oracle') : (isLoading ? 'Creating...' : 'Create Oracle')}
          </Button>
        </div>
      </div>
    </ModuleCard>
  );
};
