import { FC, useState, useMemo } from 'react';
import { CalendarIcon, Info, Sparkles } from 'lucide-react';
import awardsIcon from '@/assets/awards-icon.png';
import { ModuleCard } from './ModuleCard';
import { Button } from '@/components/ui/button';
import { FeeDisplay } from './FeeDisplay';
import { Input } from '@/components/ui/input';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useWallet } from '@solana/wallet-adapter-react';
import { cn } from '@/lib/utils';
import { format, addHours, roundToNearestMinutes } from 'date-fns';

// Award shows
type AwardShow = 'oscars' | 'grammys' | 'emmys' | 'golden_globes' | 'nobel' | 'sports' | 'custom';

const AWARD_SHOWS: Record<AwardShow, { label: string; icon: string; categories: string[] }> = {
  oscars: { 
    label: 'Academy Awards', 
    icon: '🏆',
    categories: ['Best Picture', 'Best Director', 'Best Actor', 'Best Actress', 'Best Supporting Actor', 'Best Supporting Actress']
  },
  grammys: { 
    label: 'Grammy Awards', 
    icon: '🎵',
    categories: ['Album of the Year', 'Record of the Year', 'Song of the Year', 'Best New Artist']
  },
  emmys: { 
    label: 'Emmy Awards', 
    icon: '📺',
    categories: ['Best Drama', 'Best Comedy', 'Best Limited Series', 'Best Lead Actor', 'Best Lead Actress']
  },
  golden_globes: { 
    label: 'Golden Globes', 
    icon: '🌐',
    categories: ['Best Drama Film', 'Best Comedy Film', 'Best Drama Actor', 'Best Drama Actress']
  },
  nobel: { 
    label: 'Nobel Prize', 
    icon: '🎖️',
    categories: ['Physics', 'Chemistry', 'Medicine', 'Literature', 'Peace', 'Economics']
  },
  sports: { 
    label: 'Sports Awards', 
    icon: '⚽',
    categories: ['MVP', 'Ballon d\'Or', 'Cy Young', 'Heisman Trophy', 'NBA Finals MVP']
  },
  custom: { 
    label: 'Custom Award', 
    icon: '🏅',
    categories: ['Custom']
  },
};

interface AwardsModuleProps {
  onCreateFeed: (config: {
    awardShow: AwardShow;
    category: string;
    year: number;
    question: string;
    nominee?: string;
    resolutionDate: Date;
    title: string;
  }) => void;
  isLoading: boolean;
  deploymentState?: string;
  getButtonText: (defaultText: string) => string;
}

export const AwardsModule: FC<AwardsModuleProps> = ({
  onCreateFeed,
  isLoading,
  deploymentState,
  getButtonText,
}) => {
  const { connected } = useWallet();
  const [awardShow, setAwardShow] = useState<AwardShow>('oscars');
  const [category, setCategory] = useState(AWARD_SHOWS.oscars.categories[0]);
  const [nominee, setNominee] = useState('');
  const [customQuestion, setCustomQuestion] = useState('');
  const currentYear = new Date().getFullYear();
  const [year, setYear] = useState(currentYear);
  
  // Default resolution date: ceremony date estimate
  const defaultResolutionDate = useMemo(() => {
    const now = new Date();
    const future = addHours(now, 24 * 30); // 1 month
    return roundToNearestMinutes(future, { nearestTo: 5 });
  }, []);
  
  const [resolutionDate, setResolutionDate] = useState<Date | undefined>(defaultResolutionDate);

  // Update category when award show changes
  const categories = AWARD_SHOWS[awardShow].categories;
  
  // Generate question
  const generatedQuestion = useMemo(() => {
    if (awardShow === 'custom') return customQuestion;
    
    if (nominee) {
      return `Will ${nominee} win ${category} at the ${year} ${AWARD_SHOWS[awardShow].label}?`;
    }
    return `Who will win ${category} at the ${year} ${AWARD_SHOWS[awardShow].label}?`;
  }, [awardShow, category, year, nominee, customQuestion]);

  // Generate title
  const autoGeneratedTitle = useMemo(() => {
    if (awardShow === 'custom') return customQuestion.substring(0, 60);
    return `${year} ${AWARD_SHOWS[awardShow].label}: ${category}`;
  }, [awardShow, category, year, customQuestion]);

  const isFormValid = (awardShow === 'custom' ? customQuestion.trim().length > 10 : category) && resolutionDate;

  const handleCreate = () => {
    if (!isFormValid || !resolutionDate) return;

    onCreateFeed({
      awardShow,
      category,
      year,
      question: generatedQuestion,
      nominee: nominee.trim() || undefined,
      resolutionDate,
      title: autoGeneratedTitle,
    });
  };

  return (
    <ModuleCard
      iconImage={awardsIcon}
      title="Awards"
      description="Oscars, Grammys, Nobel & sports awards"
      index={12}
    >
      <div className="space-y-4 flex-1 flex flex-col">
        {/* AI Badge */}
        <div className="flex items-center gap-2 p-2 rounded-lg bg-primary/10 border border-primary/20">
          <Sparkles className="h-4 w-4 text-primary" />
          <span className="text-xs text-primary font-medium">Powered by Claude AI</span>
        </div>

        {/* Award Show Selector */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Award Show</label>
          <Select 
            value={awardShow} 
            onValueChange={(v) => {
              const newShow = v as AwardShow;
              setAwardShow(newShow);
              setCategory(AWARD_SHOWS[newShow].categories[0]);
            }}
          >
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {Object.entries(AWARD_SHOWS).map(([key, config]) => (
                <SelectItem key={key} value={key}>
                  <span className="flex items-center gap-2">
                    <span>{config.icon}</span>
                    <span>{config.label}</span>
                  </span>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Category Selector */}
        {awardShow !== 'custom' && (
          <div className="space-y-1.5">
            <label className="text-xs text-muted-foreground">Category</label>
            <Select value={category} onValueChange={setCategory}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {categories.map((cat) => (
                  <SelectItem key={cat} value={cat}>
                    {cat}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        )}

        {/* Year Selector */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Year</label>
          <Select value={year.toString()} onValueChange={(v) => setYear(parseInt(v))}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {[currentYear, currentYear + 1].map((y) => (
                <SelectItem key={y} value={y.toString()}>
                  {y}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Nominee (optional - for binary prediction) */}
        {awardShow !== 'custom' && (
          <div className="space-y-1.5">
            <label className="text-xs text-muted-foreground">Specific Nominee (optional)</label>
            <Input
              placeholder="e.g., Oppenheimer"
              value={nominee}
              onChange={(e) => setNominee(e.target.value)}
            />
            <p className="text-[10px] text-muted-foreground">
              Leave empty to predict overall winner
            </p>
          </div>
        )}

        {/* Custom Question */}
        {awardShow === 'custom' && (
          <div className="space-y-1.5">
            <label className="text-xs text-muted-foreground">Question</label>
            <Input
              placeholder="e.g., Who will win the 2025 Ballon d'Or?"
              value={customQuestion}
              onChange={(e) => setCustomQuestion(e.target.value)}
            />
          </div>
        )}

        {/* Resolution Date */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Resolution Date (UTC)</label>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                className={cn(
                  "w-full justify-start text-left font-normal",
                  !resolutionDate && "text-muted-foreground"
                )}
              >
                <CalendarIcon className="mr-2 h-4 w-4 shrink-0" />
                <span className="truncate">{resolutionDate ? format(resolutionDate, "MMM d, yyyy") : "Select date"}</span>
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0 bg-popover border-border z-50" align="start" collisionPadding={16}>
              <Calendar
                mode="single"
                selected={resolutionDate}
                onSelect={setResolutionDate}
                disabled={(date) => date < new Date()}
                initialFocus
              />
            </PopoverContent>
          </Popover>
        </div>

        {/* Spacer */}
        <div className="flex-1" />

        {/* Footer */}
        <div className="flex items-center justify-between pt-2">
          <FeeDisplay />
          <Button
            variant="gold"
            size="sm"
            onClick={handleCreate}
            disabled={!connected || !isFormValid || isLoading}
          >
            {getButtonText('Create Oracle')}
          </Button>
        </div>
      </div>
    </ModuleCard>
  );
};
