import React, { useState, useEffect, useMemo } from 'react';
import { Rocket, Calendar, MapPin, Building2, Check, ChevronsUpDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from '@/components/ui/command';
import { ModuleCard } from './ModuleCard';
import { FeeDisplay } from './FeeDisplay';
import { useWallet } from '@solana/wallet-adapter-react';
import { supabase } from '@/integrations/supabase/client';
import { cn } from '@/lib/utils';
import { addHours, formatDateTimeForTitle } from '@/utils/utcTime';

type ConditionType = 'success' | 'scrubbed' | 'booster_landed';

interface Launch {
  id: string;
  name: string;
  net: string;
  status: {
    id: number;
    name: string;
    abbrev: string;
  };
  rocket: string;
  rocketFamily: string;
  pad: string;
  location: string;
  country: string;
  provider: string;
  providerAbbrev: string;
  mission: string | null;
  missionType: string | null;
  image: string | null;
}

interface CosmosModuleProps {
  onCreateFeed: (config: {
    launchId: string;
    launchName: string;
    rocket: string;
    provider: string;
    location: string;
    launchTime: string;
    condition: ConditionType;
    resolutionDate: Date;
    title: string;
  }) => Promise<void>;
  isLoading: boolean;
  deploymentState: string;
  getButtonText: (defaultText?: string, moduleId?: string) => string;
}

const CONDITIONS: { value: ConditionType; label: string; description: string }[] = [
  { value: 'success', label: 'Launch Successful', description: 'Payload reached intended orbit' },
  { value: 'scrubbed', label: 'Launch Scrubbed', description: 'Launch was cancelled or postponed' },
  { value: 'booster_landed', label: 'Booster Landed', description: 'First stage booster recovered successfully' },
];

const CosmosModule: React.FC<CosmosModuleProps> = ({
  onCreateFeed,
  isLoading,
  deploymentState,
  getButtonText,
}) => {
  const { connected } = useWallet();
  const [launches, setLaunches] = useState<Launch[]>([]);
  const [selectedLaunch, setSelectedLaunch] = useState<Launch | null>(null);
  const [condition, setCondition] = useState<ConditionType>('success');
  const [isFetching, setIsFetching] = useState(false);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [launchSelectorOpen, setLaunchSelectorOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  // Fetch launches on mount
  useEffect(() => {
    const fetchLaunches = async () => {
      setIsFetching(true);
      setFetchError(null);
      
      try {
        const { data, error } = await supabase.functions.invoke('space-launches');
        
        if (error) throw error;
        
        if (data?.launches) {
          setLaunches(data.launches);
        }
      } catch (err) {
        console.error('Error fetching launches:', err);
        setFetchError('Failed to load upcoming launches');
      } finally {
        setIsFetching(false);
      }
    };

    fetchLaunches();
  }, []);

  // Filter launches by search query
  const filteredLaunches = useMemo(() => {
    if (!searchQuery.trim()) return launches;
    const query = searchQuery.toLowerCase();
    return launches.filter(
      (launch) =>
        launch.name.toLowerCase().includes(query) ||
        launch.rocket.toLowerCase().includes(query) ||
        launch.provider.toLowerCase().includes(query) ||
        launch.location.toLowerCase().includes(query)
    );
  }, [launches, searchQuery]);

  // Calculate resolution date (2 hours after scheduled launch)
  const resolutionDate = useMemo(() => {
    if (!selectedLaunch) return null;
    const launchTime = new Date(selectedLaunch.net);
    return addHours(launchTime, 2);
  }, [selectedLaunch]);

  // Generate title
  const autoGeneratedTitle = useMemo(() => {
    if (!selectedLaunch || !resolutionDate) return '';
    const conditionLabel = CONDITIONS.find(c => c.value === condition)?.label || '';
    return `${selectedLaunch.name} - ${conditionLabel} by ${formatDateTimeForTitle(resolutionDate)}`;
  }, [selectedLaunch, condition, resolutionDate]);

  const handleCreate = async () => {
    if (!selectedLaunch || !resolutionDate) return;

    await onCreateFeed({
      launchId: selectedLaunch.id,
      launchName: selectedLaunch.name,
      rocket: selectedLaunch.rocket,
      provider: selectedLaunch.provider,
      location: selectedLaunch.location,
      launchTime: selectedLaunch.net,
      condition,
      resolutionDate,
      title: autoGeneratedTitle,
    });
  };

  const formatLaunchDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZoneName: 'short',
    });
  };

  const isFormValid = connected && selectedLaunch && condition;

  return (
    <ModuleCard
      title="Cosmos / Space Launches"
      description="Create oracles for rocket launches - track success, scrubs, or booster landings"
      icon={Rocket}
    >
      <div className="space-y-4">
        {/* Launch Selector */}
        <div className="space-y-2">
          <label className="text-sm font-medium text-foreground">Select Launch</label>
          <Popover open={launchSelectorOpen} onOpenChange={setLaunchSelectorOpen}>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                role="combobox"
                aria-expanded={launchSelectorOpen}
                className="w-full justify-between h-auto min-h-[44px] py-2 bg-background/50 border-border/50"
                disabled={isFetching}
              >
                {isFetching ? (
                  <span className="text-muted-foreground">Loading launches...</span>
                ) : selectedLaunch ? (
                  <div className="flex flex-col items-start text-left">
                    <span className="font-medium truncate max-w-[280px]">{selectedLaunch.name}</span>
                    <span className="text-xs text-muted-foreground">
                      {selectedLaunch.provider} • {formatLaunchDate(selectedLaunch.net)}
                    </span>
                  </div>
                ) : (
                  <span className="text-muted-foreground">Search for a launch...</span>
                )}
                <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-[400px] p-0" align="start">
              <Command>
                <CommandInput
                  placeholder="Search launches..."
                  value={searchQuery}
                  onValueChange={setSearchQuery}
                />
                <CommandList>
                  <CommandEmpty>
                    {fetchError ? fetchError : 'No launches found.'}
                  </CommandEmpty>
                  <CommandGroup>
                    {filteredLaunches.map((launch) => (
                      <CommandItem
                        key={launch.id}
                        value={launch.id}
                        onSelect={() => {
                          setSelectedLaunch(launch);
                          setLaunchSelectorOpen(false);
                          setSearchQuery('');
                        }}
                        className="flex flex-col items-start py-3"
                      >
                        <div className="flex items-center w-full">
                          <Check
                            className={cn(
                              "mr-2 h-4 w-4",
                              selectedLaunch?.id === launch.id ? "opacity-100" : "opacity-0"
                            )}
                          />
                          <div className="flex-1 min-w-0">
                            <div className="font-medium truncate">{launch.name}</div>
                            <div className="flex items-center gap-2 text-xs text-muted-foreground mt-1">
                              <span className="flex items-center gap-1">
                                <Building2 className="h-3 w-3" />
                                {launch.providerAbbrev || launch.provider}
                              </span>
                              <span>•</span>
                              <span>{launch.rocket}</span>
                            </div>
                            <div className="flex items-center gap-2 text-xs text-muted-foreground mt-1">
                              <span className="flex items-center gap-1">
                                <MapPin className="h-3 w-3" />
                                {launch.location}
                              </span>
                              <span>•</span>
                              <span className="flex items-center gap-1">
                                <Calendar className="h-3 w-3" />
                                {formatLaunchDate(launch.net)}
                              </span>
                            </div>
                          </div>
                        </div>
                      </CommandItem>
                    ))}
                  </CommandGroup>
                </CommandList>
              </Command>
            </PopoverContent>
          </Popover>
        </div>

        {/* Condition Selector */}
        <div className="space-y-2">
          <label className="text-sm font-medium text-foreground">Condition</label>
          <Select value={condition} onValueChange={(v) => setCondition(v as ConditionType)}>
            <SelectTrigger className="bg-background/50 border-border/50">
              <SelectValue placeholder="Select condition" />
            </SelectTrigger>
            <SelectContent>
              {CONDITIONS.map((cond) => (
                <SelectItem key={cond.value} value={cond.value}>
                  <div className="flex flex-col">
                    <span>{cond.label}</span>
                    <span className="text-xs text-muted-foreground">{cond.description}</span>
                  </div>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Launch Preview */}
        {selectedLaunch && (
          <div className="p-3 rounded-lg bg-purple-500/10 border border-purple-500/20">
            <div className="flex items-start gap-3">
              <div className="p-2 rounded-lg bg-purple-500/20">
                <Rocket className="h-5 w-5 text-purple-400" />
              </div>
              <div className="flex-1 min-w-0">
                <h4 className="font-medium text-foreground truncate">{selectedLaunch.name}</h4>
                <div className="text-sm text-muted-foreground mt-1 space-y-1">
                  <div className="flex items-center gap-2">
                    <Building2 className="h-3.5 w-3.5" />
                    <span>{selectedLaunch.provider}</span>
                    <span>•</span>
                    <span>{selectedLaunch.rocket}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <MapPin className="h-3.5 w-3.5" />
                    <span>{selectedLaunch.location}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Calendar className="h-3.5 w-3.5" />
                    <span>{formatLaunchDate(selectedLaunch.net)}</span>
                  </div>
                </div>
                <div className="mt-2 text-xs">
                  <span className="text-muted-foreground">Status: </span>
                  <span className={cn(
                    "font-medium",
                    selectedLaunch.status.abbrev === 'Go' && "text-green-400",
                    selectedLaunch.status.abbrev === 'TBD' && "text-yellow-400",
                    selectedLaunch.status.abbrev === 'Hold' && "text-orange-400"
                  )}>
                    {selectedLaunch.status.name}
                  </span>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Resolution Date */}
        {resolutionDate && (
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Calendar className="h-4 w-4" />
            <span>Est. Resolution: {formatLaunchDate(resolutionDate.toISOString())}</span>
          </div>
        )}

        {/* Fee Display */}
        <FeeDisplay />

        {/* Create Button */}
        <Button
          className="w-full bg-gradient-to-r from-purple-500 to-indigo-500 hover:from-purple-600 hover:to-indigo-600"
          onClick={handleCreate}
          disabled={!isFormValid || isLoading}
        >
          {getButtonText('Create Oracle', 'cosmos')}
        </Button>
      </div>
    </ModuleCard>
  );
};

export default CosmosModule;
