import { FC, useState, useMemo } from 'react';
import { CalendarIcon, Sparkles, Info } from 'lucide-react';
import aiIcon from '@/assets/ai-icon.png';
import { ModuleCard } from './ModuleCard';
import { Button } from '@/components/ui/button';
import { FeeDisplay } from './FeeDisplay';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { useWallet } from '@solana/wallet-adapter-react';
import { cn } from '@/lib/utils';
import { format, addHours, roundToNearestMinutes } from 'date-fns';

// Example predictions for inspiration
const EXAMPLE_PREDICTIONS = [
  "Will Tesla stock reach $500 before July 2025?",
  "Will Elon Musk tweet about Dogecoin this week?",
  "Will Apple announce a foldable iPhone in 2025?",
  "Will Bitcoin hit $150k before the halving?",
];

interface CustomPredictionModuleProps {
  onCreateFeed: (config: {
    question: string;
    additionalContext: string;
    sources: string[];
    resolutionDate: Date;
    title: string;
  }) => void;
  isLoading: boolean;
  deploymentState?: string;
  getButtonText: (defaultText: string) => string;
}

export const CustomPredictionModule: FC<CustomPredictionModuleProps> = ({
  onCreateFeed,
  isLoading,
  deploymentState,
  getButtonText,
}) => {
  const { connected } = useWallet();
  const [question, setQuestion] = useState('');
  const [additionalContext, setAdditionalContext] = useState('');
  const [sources, setSources] = useState('');
  
  // Default resolution date: 1 week from now
  const defaultResolutionDate = useMemo(() => {
    const now = new Date();
    const future = addHours(now, 24 * 7);
    return roundToNearestMinutes(future, { nearestTo: 5 });
  }, []);
  
  const [resolutionDate, setResolutionDate] = useState<Date | undefined>(defaultResolutionDate);

  // Generate title from question
  const autoGeneratedTitle = useMemo(() => {
    if (!question.trim()) return '';
    return question.length > 60 ? question.substring(0, 57) + '...' : question;
  }, [question]);

  // Parse sources
  const parsedSources = useMemo(() => {
    if (!sources.trim()) return [];
    return sources.split(',').map(s => s.trim()).filter(Boolean);
  }, [sources]);

  const isFormValid = question.trim().length > 15 && resolutionDate;

  const handleCreate = () => {
    if (!isFormValid || !resolutionDate) return;

    onCreateFeed({
      question: question.trim(),
      additionalContext: additionalContext.trim(),
      sources: parsedSources,
      resolutionDate,
      title: autoGeneratedTitle,
    });
  };

  // Use example prediction
  const handleUseExample = (example: string) => {
    setQuestion(example);
  };

  return (
    <ModuleCard
      iconImage={aiIcon}
      title="AI Prediction"
      description="Custom questions resolved by AI"
      index={14}
      isBeta
      betaWarning="AI resolution is in beta. Results may vary based on question clarity and available sources."
    >
      <div className="space-y-4 flex-1 flex flex-col">
        {/* AI Badge */}
        <div className="flex items-center gap-2 p-2 rounded-lg bg-primary/10 border border-primary/20">
          <Sparkles className="h-4 w-4 text-primary" />
          <span className="text-xs text-primary font-medium">Powered by Claude AI</span>
        </div>

        {/* Question Input */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Your Prediction Question</label>
          <Textarea
            placeholder="Ask a yes/no question about any future event..."
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            className="min-h-[100px] resize-none"
          />
          <p className="text-[10px] text-muted-foreground">
            Best for verifiable events with clear yes/no outcomes
          </p>
        </div>

        {/* Example Predictions */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Examples</label>
          <div className="flex flex-wrap gap-1.5">
            {EXAMPLE_PREDICTIONS.slice(0, 2).map((example) => (
              <Button
                key={example}
                variant="outline"
                size="sm"
                className="text-[10px] h-6 px-2"
                onClick={() => handleUseExample(example)}
              >
                {example.substring(0, 35)}...
              </Button>
            ))}
          </div>
        </div>

        {/* Additional Context */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Additional Context (optional)</label>
          <Input
            placeholder="e.g., Stock ticker: TSLA"
            value={additionalContext}
            onChange={(e) => setAdditionalContext(e.target.value)}
          />
        </div>

        {/* Sources */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Preferred Sources (optional)</label>
          <Input
            placeholder="e.g., Twitter, Bloomberg, CoinDesk"
            value={sources}
            onChange={(e) => setSources(e.target.value)}
          />
          <p className="text-[10px] text-muted-foreground">
            Comma-separated list of sources AI should prioritize
          </p>
        </div>

        {/* Resolution Date */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Resolution Date (UTC)</label>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                className={cn(
                  "w-full justify-start text-left font-normal",
                  !resolutionDate && "text-muted-foreground"
                )}
              >
                <CalendarIcon className="mr-2 h-4 w-4 shrink-0" />
                <span className="truncate">{resolutionDate ? format(resolutionDate, "MMM d, yyyy") : "Select date"}</span>
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0 bg-popover border-border z-50" align="start" collisionPadding={16}>
              <Calendar
                mode="single"
                selected={resolutionDate}
                onSelect={setResolutionDate}
                disabled={(date) => date < new Date()}
                initialFocus
              />
            </PopoverContent>
          </Popover>
        </div>

        {/* Info */}
        <div className="p-2 rounded-lg bg-muted/50 border">
          <p className="text-[10px] text-muted-foreground flex items-start gap-1.5">
            <Info className="h-3 w-3 mt-0.5 shrink-0" />
            AI will search the web and analyze sources to determine the factual outcome at resolution time. Best for events with clear, verifiable outcomes.
          </p>
        </div>

        {/* Spacer */}
        <div className="flex-1" />

        {/* Footer */}
        <div className="flex items-center justify-between pt-2">
          <FeeDisplay />
          <Button
            variant="gold"
            size="sm"
            onClick={handleCreate}
            disabled={!connected || !isFormValid || isLoading}
          >
            {getButtonText('Create Oracle')}
          </Button>
        </div>
      </div>
    </ModuleCard>
  );
};
