import { FC, useState, useMemo } from 'react';
import { CalendarIcon, Info, Sparkles } from 'lucide-react';
import economyIcon from '@/assets/economy-icon.png';
import { ModuleCard } from './ModuleCard';
import { Button } from '@/components/ui/button';
import { FeeDisplay } from './FeeDisplay';
import { Input } from '@/components/ui/input';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useWallet } from '@solana/wallet-adapter-react';
import { cn } from '@/lib/utils';
import { format, addHours, roundToNearestMinutes } from 'date-fns';

// Economic indicators
type IndicatorType = 'fed_rate' | 'cpi' | 'gdp' | 'unemployment' | 'custom';

const INDICATORS: Record<IndicatorType, { label: string; icon: string; description: string; format: string }> = {
  fed_rate: { label: 'Fed Rate Decision', icon: '🏛️', description: 'FOMC interest rate decisions', format: 'raise/cut/hold' },
  cpi: { label: 'CPI / Inflation', icon: '📈', description: 'Consumer Price Index data', format: 'percentage' },
  gdp: { label: 'GDP Growth', icon: '💹', description: 'Gross Domestic Product', format: 'percentage' },
  unemployment: { label: 'Unemployment Rate', icon: '👷', description: 'US unemployment statistics', format: 'percentage' },
  custom: { label: 'Custom Indicator', icon: '📊', description: 'Any economic metric', format: 'custom' },
};

// Common FOMC meeting schedule hints
const FOMC_DATES_2025 = [
  'Jan 28-29', 'Mar 18-19', 'May 6-7', 'Jun 17-18',
  'Jul 29-30', 'Sep 16-17', 'Nov 4-5', 'Dec 16-17'
];

interface EconomyModuleProps {
  onCreateFeed: (config: {
    indicator: IndicatorType;
    dataSource: string;
    period: string;
    question: string;
    resolutionDate: Date;
    title: string;
  }) => void;
  isLoading: boolean;
  deploymentState?: string;
  getButtonText: (defaultText: string) => string;
}

export const EconomyModule: FC<EconomyModuleProps> = ({
  onCreateFeed,
  isLoading,
  deploymentState,
  getButtonText,
}) => {
  const { connected } = useWallet();
  const [indicator, setIndicator] = useState<IndicatorType>('fed_rate');
  const [period, setPeriod] = useState('');
  const [question, setQuestion] = useState('');
  
  // Default resolution date: 1 week from now
  const defaultResolutionDate = useMemo(() => {
    const now = new Date();
    const future = addHours(now, 24 * 7);
    return roundToNearestMinutes(future, { nearestTo: 5 });
  }, []);
  
  const [resolutionDate, setResolutionDate] = useState<Date | undefined>(defaultResolutionDate);

  // Auto-generate question based on indicator
  const suggestedQuestion = useMemo(() => {
    switch (indicator) {
      case 'fed_rate':
        return `Will the Fed raise, cut, or hold rates at the ${period || 'upcoming'} FOMC meeting?`;
      case 'cpi':
        return `What will be the CPI year-over-year change for ${period || 'the upcoming release'}?`;
      case 'gdp':
        return `What will be the GDP growth rate for ${period || 'Q1 2025'}?`;
      case 'unemployment':
        return `What will be the unemployment rate for ${period || 'the upcoming release'}?`;
      default:
        return question;
    }
  }, [indicator, period, question]);

  // Generate title
  const autoGeneratedTitle = useMemo(() => {
    const indicatorLabel = INDICATORS[indicator].label;
    const shortPeriod = period.length > 20 ? period.substring(0, 17) + '...' : period;
    return `${indicatorLabel}${shortPeriod ? ` (${shortPeriod})` : ''}`;
  }, [indicator, period]);

  const isFormValid = (indicator === 'custom' ? question.trim().length > 10 : true) && resolutionDate;

  const handleCreate = () => {
    if (!isFormValid || !resolutionDate) return;

    onCreateFeed({
      indicator,
      dataSource: indicator === 'fed_rate' ? 'Federal Reserve' : 'BLS/BEA',
      period: period.trim(),
      question: indicator === 'custom' ? question.trim() : suggestedQuestion,
      resolutionDate,
      title: autoGeneratedTitle,
    });
  };

  return (
    <ModuleCard
      iconImage={economyIcon}
      title="Economy"
      description="Fed rates, CPI, GDP & economic data"
      index={11}
    >
      <div className="space-y-4 flex-1 flex flex-col">
        {/* AI Badge */}
        <div className="flex items-center gap-2 p-2 rounded-lg bg-primary/10 border border-primary/20">
          <Sparkles className="h-4 w-4 text-primary" />
          <span className="text-xs text-primary font-medium">Powered by Claude AI</span>
        </div>

        {/* Indicator Selector */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Economic Indicator</label>
          <Select value={indicator} onValueChange={(v) => setIndicator(v as IndicatorType)}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {Object.entries(INDICATORS).map(([key, config]) => (
                <SelectItem key={key} value={key}>
                  <span className="flex items-center gap-2">
                    <span>{config.icon}</span>
                    <span>{config.label}</span>
                  </span>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Period Input */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">
            {indicator === 'fed_rate' ? 'FOMC Meeting' : 'Period/Date'}
          </label>
          <Input
            placeholder={indicator === 'fed_rate' ? 'e.g., March 2025' : 'e.g., Q1 2025'}
            value={period}
            onChange={(e) => setPeriod(e.target.value)}
          />
          {indicator === 'fed_rate' && (
            <p className="text-[10px] text-muted-foreground">
              2025 FOMC: {FOMC_DATES_2025.slice(0, 4).join(', ')}...
            </p>
          )}
        </div>

        {/* Custom Question (only for custom indicator) */}
        {indicator === 'custom' && (
          <div className="space-y-1.5">
            <label className="text-xs text-muted-foreground">Question</label>
            <Input
              placeholder="e.g., Will core PCE exceed 3%?"
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
            />
          </div>
        )}

        {/* Preview Question */}
        {indicator !== 'custom' && (
          <div className="space-y-1.5">
            <label className="text-xs text-muted-foreground">Question Preview</label>
            <div className="p-2.5 rounded-md border bg-muted/50 text-sm">
              {suggestedQuestion}
            </div>
          </div>
        )}

        {/* Resolution Date */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Resolution Date (UTC)</label>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                className={cn(
                  "w-full justify-start text-left font-normal",
                  !resolutionDate && "text-muted-foreground"
                )}
              >
                <CalendarIcon className="mr-2 h-4 w-4 shrink-0" />
                <span className="truncate">{resolutionDate ? format(resolutionDate, "MMM d, yyyy") : "Select date"}</span>
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0 bg-popover border-border z-50" align="start" collisionPadding={16}>
              <Calendar
                mode="single"
                selected={resolutionDate}
                onSelect={setResolutionDate}
                disabled={(date) => date < new Date()}
                initialFocus
              />
            </PopoverContent>
          </Popover>
        </div>

        {/* Info */}
        <p className="text-[10px] text-muted-foreground flex items-center gap-1">
          <Info className="h-3 w-3" />
          AI resolves using official Fed/BLS data
        </p>

        {/* Spacer */}
        <div className="flex-1" />

        {/* Footer */}
        <div className="flex items-center justify-between pt-2">
          <FeeDisplay />
          <Button
            variant="gold"
            size="sm"
            onClick={handleCreate}
            disabled={!connected || !isFormValid || isLoading}
          >
            {getButtonText('Create Oracle')}
          </Button>
        </div>
      </div>
    </ModuleCard>
  );
};
