import { FC, useState, useCallback, useEffect, useMemo } from 'react';
import { ModuleCard } from './ModuleCard';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { FeeDisplay } from './FeeDisplay';
import { CalendarIcon, Rocket, AlertCircle, CheckCircle2, Loader2, Clock, XCircle } from 'lucide-react';
import { format } from 'date-fns';
import { cn } from '@/lib/utils';
import { supabase } from '@/integrations/supabase/client';
import { useWallet } from '@solana/wallet-adapter-react';
import { DeploymentState } from '@/hooks/useCreateFeed';
import { 
  getDefaultLocalResolutionDate, 
  getDefaultLocalHour, 
  getDefaultLocalMinute, 
  createDateTimeFromLocal, 
  formatDateTimeForTitle,
  isValidFutureTime,
  getTimezoneAbbr
} from '@/utils/utcTime';
import launchpadIcon from '@/assets/launchpad-icon.png';

interface LaunchpadModuleProps {
  onCreateFeed: (config: {
    launchpad: 'pumpfun' | 'letsbonk';
    tokenAddress: string;
    tokenSymbol: string;
    tokenName: string;
    tokenImage: string | null;
    initialProgress: number;
    resolutionDate: Date;
    title: string;
  }) => Promise<void>;
  isLoading: boolean;
  deploymentState: DeploymentState;
  getButtonText: (defaultText: string) => string;
}

interface TokenStatus {
  tokenAddress: string;
  launchpad: string;
  tokenName: string;
  tokenSymbol: string;
  tokenImage: string | null;
  bondingProgress: number;
  isGraduated: boolean;
}

export const LaunchpadModule: FC<LaunchpadModuleProps> = ({
  onCreateFeed,
  isLoading,
  deploymentState,
  getButtonText,
}) => {
  const { connected } = useWallet();
  const [launchpad, setLaunchpad] = useState<'pumpfun' | 'letsbonk'>('pumpfun');
  const [tokenAddress, setTokenAddress] = useState('');
  const [tokenStatus, setTokenStatus] = useState<TokenStatus | null>(null);
  const [isFetching, setIsFetching] = useState(false);
  const [fetchError, setFetchError] = useState<string | null>(null);
  
  // Initialize with smart local defaults (same as Crypto/Memecoin)
  const defaultDate = getDefaultLocalResolutionDate();
  const [resolutionDate, setResolutionDate] = useState<Date>(defaultDate);
  const [selectedHour, setSelectedHour] = useState<string>(getDefaultLocalHour(defaultDate));
  const [selectedMinute, setSelectedMinute] = useState<string>(getDefaultLocalMinute(defaultDate));
  const tzAbbr = getTimezoneAbbr();

  // Calculate full resolution datetime
  const fullResolutionDate = useMemo(() => {
    if (!resolutionDate) return undefined;
    return createDateTimeFromLocal(resolutionDate, selectedHour, selectedMinute);
  }, [resolutionDate, selectedHour, selectedMinute]);

  // Validate minimum time in future
  const isValidTime = fullResolutionDate ? isValidFutureTime(fullResolutionDate) : true;

  const fetchTokenStatus = useCallback(async (address: string) => {
    if (!address || address.length < 32) {
      return;
    }

    setIsFetching(true);
    setFetchError(null);
    setTokenStatus(null);

    try {
      const { data, error } = await supabase.functions.invoke('launchpad-status', {
        body: { tokenAddress: address, launchpad },
      });

      if (error) throw error;
      if (!data.success) throw new Error(data.error);

      setTokenStatus(data.data);
    } catch (err: any) {
      setFetchError(err.message || 'Failed to fetch token status');
    } finally {
      setIsFetching(false);
    }
  }, [launchpad]);

  // Auto-fetch when token address changes (with debounce)
  useEffect(() => {
    if (tokenAddress.length >= 32) {
      const timer = setTimeout(() => {
        fetchTokenStatus(tokenAddress);
      }, 500);
      return () => clearTimeout(timer);
    } else {
      setTokenStatus(null);
      setFetchError(null);
    }
  }, [tokenAddress, launchpad, fetchTokenStatus]);

  // Auto-generate feed title
  const autoGeneratedTitle = useMemo(() => {
    if (!tokenStatus || !fullResolutionDate) return '';
    const dateLabel = formatDateTimeForTitle(fullResolutionDate);
    return `${tokenStatus.tokenSymbol} graduates by ${dateLabel}`;
  }, [tokenStatus, fullResolutionDate]);

  const handleCreate = async () => {
    if (!tokenStatus || !fullResolutionDate) return;

    await onCreateFeed({
      launchpad,
      tokenAddress: tokenStatus.tokenAddress,
      tokenSymbol: tokenStatus.tokenSymbol,
      tokenName: tokenStatus.tokenName,
      tokenImage: tokenStatus.tokenImage,
      initialProgress: tokenStatus.bondingProgress,
      resolutionDate: fullResolutionDate,
      title: autoGeneratedTitle,
    });
  };

  const canCreate = connected && tokenStatus && !tokenStatus.isGraduated && fullResolutionDate && isValidTime && !isLoading;

  return (
    <ModuleCard
      title="Launchpad Graduation"
      description="Predict if a token will graduate from bonding curve"
      iconImage={launchpadIcon}
    >
      <div className="space-y-4 flex-1 flex flex-col">
        {/* Launchpad Selector */}
        <div className="space-y-2">
          <Label className="text-sm font-medium text-foreground">Launchpad</Label>
          <Select value={launchpad} onValueChange={(v) => {
            setLaunchpad(v as 'pumpfun' | 'letsbonk');
            setTokenStatus(null);
            setFetchError(null);
          }}>
            <SelectTrigger className="w-full bg-background border-border">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="pumpfun">Pump.fun</SelectItem>
              <SelectItem value="letsbonk">LetsBonk.fun</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Token Address Input */}
        <div className="space-y-2">
          <Label className="text-sm font-medium text-foreground">Token Address</Label>
          <div className="relative">
            <Input
              placeholder="Paste token contract address..."
              value={tokenAddress}
              onChange={(e) => setTokenAddress(e.target.value)}
              className="bg-background border-border font-mono text-sm pr-10"
            />
            {isFetching && (
              <Loader2 className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 animate-spin text-muted-foreground" />
            )}
          </div>

          {/* Token Preview */}
          {tokenStatus && !isFetching && (
            <div className="p-3 bg-green-500/10 border border-green-500/20 rounded-md space-y-3">
              <div className="flex items-center gap-3">
                {tokenStatus.tokenImage && (
                  <img 
                    src={tokenStatus.tokenImage} 
                    alt={tokenStatus.tokenSymbol}
                    className="w-10 h-10 rounded-full border border-green-500/30"
                    onError={(e) => { e.currentTarget.style.display = 'none'; }}
                  />
                )}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="h-4 w-4 text-green-500 shrink-0" />
                    <span className="text-green-600 font-medium">{tokenStatus.tokenName}</span>
                  </div>
                  <div className="text-sm text-muted-foreground">${tokenStatus.tokenSymbol}</div>
                </div>
              </div>

              {/* Bonding Progress */}
              <div className="space-y-1">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Bonding Progress</span>
                  <span className="font-medium">{tokenStatus.bondingProgress.toFixed(1)}%</span>
                </div>
                <Progress value={tokenStatus.bondingProgress} className="h-2" />
              </div>

              {/* Graduation Status */}
              {tokenStatus.isGraduated ? (
                <div className="flex items-center gap-2 text-green-500 text-sm">
                  <CheckCircle2 className="h-4 w-4" />
                  Already graduated - cannot create market
                </div>
              ) : (
                <div className="flex items-center gap-2 text-amber-500 text-sm">
                  <Rocket className="h-4 w-4" />
                  Still on bonding curve - eligible for prediction
                </div>
              )}
            </div>
          )}

          {/* Error Message */}
          {fetchError && !isFetching && (
            <div className="flex items-center gap-2 p-2 bg-destructive/10 border border-destructive/20 rounded-md">
              <XCircle className="h-4 w-4 text-destructive shrink-0" />
              <span className="text-sm text-destructive">{fetchError}</span>
            </div>
          )}
        </div>

        {/* Resolution Date & Time (Local) */}
        <div className="space-y-2">
          <Label className="text-sm font-medium text-foreground">
            Graduation Deadline <span className="text-muted-foreground text-xs">({tzAbbr})</span>
          </Label>
          <div className="flex flex-wrap gap-2">
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className={cn(
                    "flex-1 min-w-[140px] justify-start text-left font-normal bg-background border-border",
                    !resolutionDate && "text-muted-foreground"
                  )}
                >
                  <CalendarIcon className="mr-2 h-4 w-4 shrink-0" />
                  <span className="truncate">{resolutionDate ? format(resolutionDate, "MMM d, yyyy") : "Select date"}</span>
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0 bg-popover border-border z-50" align="start" collisionPadding={16}>
                <Calendar
                  mode="single"
                  selected={resolutionDate}
                  onSelect={setResolutionDate}
                  disabled={(date) => date < new Date()}
                  initialFocus
                  className="p-3 pointer-events-auto"
                />
              </PopoverContent>
            </Popover>
            
            {/* Time Selection */}
            <div className="flex items-center gap-1">
              <Clock className="h-4 w-4 text-muted-foreground" />
              <Input
                type="text"
                inputMode="numeric"
                maxLength={2}
                value={selectedHour}
                onChange={(e) => {
                  const val = e.target.value.replace(/\D/g, '').slice(0, 2);
                  setSelectedHour(val);
                }}
                onBlur={(e) => {
                  let val = parseInt(e.target.value) || 0;
                  val = Math.min(23, Math.max(0, val));
                  setSelectedHour(val.toString().padStart(2, '0'));
                }}
                className="w-14 bg-background border-border text-center"
                placeholder="HH"
              />
              <span className="text-muted-foreground font-medium">:</span>
              <Input
                type="text"
                inputMode="numeric"
                maxLength={2}
                value={selectedMinute}
                onChange={(e) => {
                  const val = e.target.value.replace(/\D/g, '').slice(0, 2);
                  setSelectedMinute(val);
                }}
                onBlur={(e) => {
                  let val = parseInt(e.target.value) || 0;
                  val = Math.min(59, Math.max(0, val));
                  setSelectedMinute(val.toString().padStart(2, '0'));
                }}
                className="w-14 bg-background border-border text-center"
                placeholder="MM"
              />
            </div>
          </div>
          
          {/* Time Validation Error */}
          {fullResolutionDate && !isValidTime && (
            <p className="text-xs text-destructive flex items-center gap-1">
              <XCircle className="h-3 w-3" />
              Minimum duration is 10 minutes from now
            </p>
          )}
          
          <p className="text-xs text-muted-foreground">
            If token graduates before this time = YES wins. Otherwise = NO wins.
          </p>
        </div>

        {/* Auto-generated Feed Title Preview */}
        {autoGeneratedTitle && (
          <div className="space-y-2">
            <Label className="text-sm font-medium text-muted-foreground">Feed Title (auto)</Label>
            <div className="px-3 py-2 bg-muted/50 rounded-md border border-border/50 h-10 flex items-center">
              <span className="text-sm text-foreground truncate">{autoGeneratedTitle}</span>
            </div>
          </div>
        )}
        
        {/* Spacer to push button to bottom */}
        <div className="flex-1" />

        <div className="flex items-center justify-between pt-2">
          <FeeDisplay />
          <Button
            variant={deploymentState === 'success' ? 'default' : 'gold'}
            size="sm"
            onClick={handleCreate}
            disabled={!canCreate}
            className={deploymentState === 'success' ? 'bg-green-500 hover:bg-green-600' : ''}
          >
            {getButtonText('Create Oracle')}
          </Button>
        </div>
      </div>
    </ModuleCard>
  );
};