import { FC, useState, useMemo } from 'react';
import { CalendarIcon, Info, Sparkles } from 'lucide-react';
import legalIcon from '@/assets/legal-icon.png';
import { ModuleCard } from './ModuleCard';
import { Button } from '@/components/ui/button';
import { FeeDisplay } from './FeeDisplay';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useWallet } from '@solana/wallet-adapter-react';
import { cn } from '@/lib/utils';
import { format, addHours, roundToNearestMinutes } from 'date-fns';

// Case types
type CaseType = 'sec' | 'antitrust' | 'patent' | 'criminal' | 'civil' | 'custom';

const CASE_TYPES: Record<CaseType, { label: string; icon: string; description: string }> = {
  sec: { label: 'SEC / Crypto', icon: '⚖️', description: 'Securities and crypto enforcement' },
  antitrust: { label: 'Antitrust', icon: '🏢', description: 'Competition and monopoly cases' },
  patent: { label: 'Patent / IP', icon: '📜', description: 'Intellectual property disputes' },
  criminal: { label: 'Criminal', icon: '🔒', description: 'Criminal prosecutions' },
  civil: { label: 'Civil', icon: '📋', description: 'Civil lawsuits and disputes' },
  custom: { label: 'Custom Case', icon: '⚙️', description: 'Any legal proceeding' },
};

// Notable ongoing cases
const NOTABLE_CASES = [
  { name: 'SEC vs Coinbase', type: 'sec', parties: 'SEC, Coinbase' },
  { name: 'SEC vs Ripple (XRP)', type: 'sec', parties: 'SEC, Ripple Labs' },
  { name: 'FTC vs Meta', type: 'antitrust', parties: 'FTC, Meta Platforms' },
  { name: 'Epic vs Apple', type: 'antitrust', parties: 'Epic Games, Apple' },
];

interface LegalModuleProps {
  onCreateFeed: (config: {
    caseType: CaseType;
    caseName: string;
    court: string;
    parties: string;
    question: string;
    resolutionDate: Date;
    title: string;
  }) => void;
  isLoading: boolean;
  deploymentState?: string;
  getButtonText: (defaultText: string) => string;
}

export const LegalModule: FC<LegalModuleProps> = ({
  onCreateFeed,
  isLoading,
  deploymentState,
  getButtonText,
}) => {
  const { connected } = useWallet();
  const [caseType, setCaseType] = useState<CaseType>('sec');
  const [caseName, setCaseName] = useState('');
  const [court, setCourt] = useState('');
  const [parties, setParties] = useState('');
  const [question, setQuestion] = useState('');
  
  // Default resolution date: 3 months from now
  const defaultResolutionDate = useMemo(() => {
    const now = new Date();
    const future = addHours(now, 24 * 90); // ~3 months
    return roundToNearestMinutes(future, { nearestTo: 5 });
  }, []);
  
  const [resolutionDate, setResolutionDate] = useState<Date | undefined>(defaultResolutionDate);

  // Generate question based on case type
  const suggestedQuestion = useMemo(() => {
    if (question) return question;
    if (!caseName) return '';
    
    switch (caseType) {
      case 'sec':
        return `Will the SEC win against ${caseName.includes('vs') ? caseName.split('vs')[1]?.trim() : caseName}?`;
      case 'antitrust':
        return `Will the court rule in favor of the plaintiff in ${caseName}?`;
      case 'criminal':
        return `Will the defendant be found guilty in ${caseName}?`;
      default:
        return `What will be the outcome of ${caseName}?`;
    }
  }, [caseType, caseName, question]);

  // Generate title
  const autoGeneratedTitle = useMemo(() => {
    if (!caseName) return 'Legal Case Oracle';
    const shortName = caseName.length > 40 ? caseName.substring(0, 37) + '...' : caseName;
    return `${CASE_TYPES[caseType].label}: ${shortName}`;
  }, [caseType, caseName]);

  const isFormValid = caseName.trim().length > 3 && resolutionDate;

  const handleCreate = () => {
    if (!isFormValid || !resolutionDate) return;

    onCreateFeed({
      caseType,
      caseName: caseName.trim(),
      court: court.trim(),
      parties: parties.trim(),
      question: suggestedQuestion,
      resolutionDate,
      title: autoGeneratedTitle,
    });
  };

  // Quick fill from notable cases
  const handleNotableCase = (notable: typeof NOTABLE_CASES[0]) => {
    setCaseName(notable.name);
    setCaseType(notable.type as CaseType);
    setParties(notable.parties);
  };

  return (
    <ModuleCard
      iconImage={legalIcon}
      title="Legal"
      description="Court cases, SEC, antitrust verdicts"
      index={13}
    >
      <div className="space-y-4 flex-1 flex flex-col">
        {/* AI Badge */}
        <div className="flex items-center gap-2 p-2 rounded-lg bg-primary/10 border border-primary/20">
          <Sparkles className="h-4 w-4 text-primary" />
          <span className="text-xs text-primary font-medium">Powered by Claude AI</span>
        </div>

        {/* Case Type Selector */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Case Type</label>
          <Select value={caseType} onValueChange={(v) => setCaseType(v as CaseType)}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {Object.entries(CASE_TYPES).map(([key, config]) => (
                <SelectItem key={key} value={key}>
                  <span className="flex items-center gap-2">
                    <span>{config.icon}</span>
                    <span>{config.label}</span>
                  </span>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Notable Cases Quick Select */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Notable Cases</label>
          <div className="flex flex-wrap gap-1.5">
            {NOTABLE_CASES.slice(0, 3).map((notable) => (
              <Button
                key={notable.name}
                variant="outline"
                size="sm"
                className="text-xs h-7 px-2"
                onClick={() => handleNotableCase(notable)}
              >
                {notable.name}
              </Button>
            ))}
          </div>
        </div>

        {/* Case Name Input */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Case Name</label>
          <Input
            placeholder="e.g., SEC vs Coinbase"
            value={caseName}
            onChange={(e) => setCaseName(e.target.value)}
          />
        </div>

        {/* Parties */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Parties (optional)</label>
          <Input
            placeholder="e.g., SEC, Coinbase Global Inc."
            value={parties}
            onChange={(e) => setParties(e.target.value)}
          />
        </div>

        {/* Court */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Court (optional)</label>
          <Input
            placeholder="e.g., US District Court, Southern District of NY"
            value={court}
            onChange={(e) => setCourt(e.target.value)}
          />
        </div>

        {/* Custom Question */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Question (optional)</label>
          <Input
            placeholder="Leave empty for auto-generated question"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
          />
        </div>

        {/* Resolution Date */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Expected Resolution (UTC)</label>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                className={cn(
                  "w-full justify-start text-left font-normal",
                  !resolutionDate && "text-muted-foreground"
                )}
              >
                <CalendarIcon className="mr-2 h-4 w-4 shrink-0" />
                <span className="truncate">{resolutionDate ? format(resolutionDate, "MMM d, yyyy") : "Select date"}</span>
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0 bg-popover border-border z-50" align="start" collisionPadding={16}>
              <Calendar
                mode="single"
                selected={resolutionDate}
                onSelect={setResolutionDate}
                disabled={(date) => date < new Date()}
                initialFocus
              />
            </PopoverContent>
          </Popover>
        </div>

        {/* Info */}
        <p className="text-[10px] text-muted-foreground flex items-center gap-1">
          <Info className="h-3 w-3" />
          AI monitors court filings and official rulings
        </p>

        {/* Spacer */}
        <div className="flex-1" />

        {/* Footer */}
        <div className="flex items-center justify-between pt-2">
          <FeeDisplay />
          <Button
            variant="gold"
            size="sm"
            onClick={handleCreate}
            disabled={!connected || !isFormValid || isLoading}
          >
            {getButtonText('Create Oracle')}
          </Button>
        </div>
      </div>
    </ModuleCard>
  );
};
