import { FC, useState, useMemo } from 'react';
import { CalendarIcon, Info, Sparkles } from 'lucide-react';
import politicsIcon from '@/assets/politics-icon.png';
import { ModuleCard } from './ModuleCard';
import { Button } from '@/components/ui/button';
import { FeeDisplay } from './FeeDisplay';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useWallet } from '@solana/wallet-adapter-react';
import { cn } from '@/lib/utils';
import { format, addHours, startOfHour, roundToNearestMinutes } from 'date-fns';

// Event types for politics module
type EventType = 'election' | 'legislation' | 'appointment' | 'policy';

const EVENT_TYPES: Record<EventType, { label: string; icon: string; description: string }> = {
  election: { label: 'Election', icon: '🗳️', description: 'Presidential, congressional, local elections' },
  legislation: { label: 'Legislation', icon: '📜', description: 'Bills, laws, amendments' },
  appointment: { label: 'Appointment', icon: '👔', description: 'Cabinet, judiciary, agency heads' },
  policy: { label: 'Policy', icon: '📋', description: 'Executive orders, regulations' },
};

const REGIONS = [
  { value: 'us', label: '🇺🇸 United States' },
  { value: 'eu', label: '🇪🇺 European Union' },
  { value: 'uk', label: '🇬🇧 United Kingdom' },
  { value: 'global', label: '🌍 Global' },
];

interface PoliticsModuleProps {
  onCreateFeed: (config: {
    eventType: EventType;
    region: string;
    question: string;
    additionalContext: string;
    resolutionDate: Date;
    title: string;
  }) => void;
  isLoading: boolean;
  deploymentState?: string;
  getButtonText: (defaultText: string) => string;
}

export const PoliticsModule: FC<PoliticsModuleProps> = ({
  onCreateFeed,
  isLoading,
  deploymentState,
  getButtonText,
}) => {
  const { connected } = useWallet();
  const [eventType, setEventType] = useState<EventType>('election');
  const [region, setRegion] = useState('us');
  const [question, setQuestion] = useState('');
  const [additionalContext, setAdditionalContext] = useState('');
  
  // Default resolution date: 1 week from now
  const defaultResolutionDate = useMemo(() => {
    const now = new Date();
    const future = addHours(now, 24 * 7); // 1 week
    return roundToNearestMinutes(future, { nearestTo: 5 });
  }, []);
  
  const [resolutionDate, setResolutionDate] = useState<Date | undefined>(defaultResolutionDate);

  // Generate title from question
  const autoGeneratedTitle = useMemo(() => {
    if (!question.trim()) return '';
    const eventLabel = EVENT_TYPES[eventType].label;
    const shortQuestion = question.length > 50 ? question.substring(0, 47) + '...' : question;
    return `${eventLabel}: ${shortQuestion}`;
  }, [question, eventType]);

  const isFormValid = question.trim().length > 10 && resolutionDate;

  const handleCreate = () => {
    if (!isFormValid || !resolutionDate) return;

    onCreateFeed({
      eventType,
      region,
      question: question.trim(),
      additionalContext: additionalContext.trim(),
      resolutionDate,
      title: autoGeneratedTitle,
    });
  };

  return (
    <ModuleCard
      iconImage={politicsIcon}
      title="Politics"
      description="Elections, legislation & policy oracles"
      index={10}
    >
      <div className="space-y-4 flex-1 flex flex-col">
        {/* AI Badge */}
        <div className="flex items-center gap-2 p-2 rounded-lg bg-primary/10 border border-primary/20">
          <Sparkles className="h-4 w-4 text-primary" />
          <span className="text-xs text-primary font-medium">Powered by Claude AI</span>
        </div>

        {/* Event Type Selector */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Event Type</label>
          <Select value={eventType} onValueChange={(v) => setEventType(v as EventType)}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {Object.entries(EVENT_TYPES).map(([key, config]) => (
                <SelectItem key={key} value={key}>
                  <span className="flex items-center gap-2">
                    <span>{config.icon}</span>
                    <span>{config.label}</span>
                  </span>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Region Selector */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Region</label>
          <Select value={region} onValueChange={setRegion}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {REGIONS.map((r) => (
                <SelectItem key={r.value} value={r.value}>
                  {r.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Question Input */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Question (Yes/No format)</label>
          <Textarea
            placeholder="e.g., Will the infrastructure bill pass in the Senate?"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            className="min-h-[80px] resize-none"
          />
          <p className="text-[10px] text-muted-foreground flex items-center gap-1">
            <Info className="h-3 w-3" />
            AI will resolve this based on official sources
          </p>
        </div>

        {/* Additional Context */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Additional Context (optional)</label>
          <Input
            placeholder="e.g., Bill number H.R. 3684"
            value={additionalContext}
            onChange={(e) => setAdditionalContext(e.target.value)}
          />
        </div>

        {/* Resolution Date */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Resolution Date (UTC)</label>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                className={cn(
                  "w-full justify-start text-left font-normal",
                  !resolutionDate && "text-muted-foreground"
                )}
              >
                <CalendarIcon className="mr-2 h-4 w-4 shrink-0" />
                <span className="truncate">{resolutionDate ? format(resolutionDate, "MMM d, yyyy") : "Select date"}</span>
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0 bg-popover border-border z-50" align="start" collisionPadding={16}>
              <Calendar
                mode="single"
                selected={resolutionDate}
                onSelect={setResolutionDate}
                disabled={(date) => date < new Date()}
                initialFocus
              />
            </PopoverContent>
          </Popover>
        </div>

        {/* Spacer */}
        <div className="flex-1" />

        {/* Footer */}
        <div className="flex items-center justify-between pt-2">
          <FeeDisplay />
          <Button
            variant="gold"
            size="sm"
            onClick={handleCreate}
            disabled={!connected || !isFormValid || isLoading}
          >
            {getButtonText('Create Oracle')}
          </Button>
        </div>
      </div>
    </ModuleCard>
  );
};
