import { FC, useState, useMemo, useEffect } from 'react';
import { CalendarIcon, Loader2, CheckCircle, XCircle, Clock, Heart, Repeat, ExternalLink } from 'lucide-react';
import xIcon from '@/assets/x-icon.png';
import { ModuleCard } from './ModuleCard';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Skeleton } from '@/components/ui/skeleton';
import { FeeDisplay } from './FeeDisplay';
import { useWallet } from '@solana/wallet-adapter-react';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';
import { toast } from '@/hooks/use-toast';
import { 
  getDefaultLocalResolutionDate, 
  getDefaultLocalHour, 
  getDefaultLocalMinute, 
  createDateTimeFromLocal, 
  formatDateTimeForTitle,
  isValidFutureTimeOneHour,
  getTimezoneAbbr,
  addHours
} from '@/utils/utcTime';
import { 
  fetchTweetMetrics, 
  TweetMetrics, 
  isValidTweetUrl, 
  formatMetricNumber,
  getMetricLabel 
} from '@/services/socialDataService';

import { DeploymentState } from '@/hooks/useCreateFeed';

type SocialMetric = 'likes' | 'retweets';

interface SocialModuleProps {
  onCreateFeed: (config: { 
    tweetUrl: string;
    metric: SocialMetric;
    resolutionDate: Date;
    title: string;
    tweetData: TweetMetrics;
  }) => void;
  isLoading?: boolean;
  deploymentState?: DeploymentState;
  getButtonText?: (defaultText?: string) => string;
}

const METRIC_OPTIONS: { value: SocialMetric; label: string; icon: typeof Heart }[] = [
  { value: 'likes', label: 'Likes Count', icon: Heart },
  { value: 'retweets', label: 'Retweets Count', icon: Repeat },
];

export const SocialModule: FC<SocialModuleProps> = ({ onCreateFeed, isLoading, deploymentState, getButtonText }) => {
  const { connected } = useWallet();
  const [tweetUrl, setTweetUrl] = useState('');
  const [selectedMetric, setSelectedMetric] = useState<SocialMetric>('likes');
  
  // Initialize with default: now + 1 hour
  const defaultDate = addHours(new Date(), 1);
  const [resolutionDate, setResolutionDate] = useState<Date>(defaultDate);
  const [selectedHour, setSelectedHour] = useState<string>(getDefaultLocalHour(defaultDate));
  const [selectedMinute, setSelectedMinute] = useState<string>(getDefaultLocalMinute(defaultDate));
  const tzAbbr = getTimezoneAbbr();
  
  // Tweet data state
  const [tweetData, setTweetData] = useState<TweetMetrics | null>(null);
  const [isFetching, setIsFetching] = useState(false);
  const [fetchError, setFetchError] = useState<string | null>(null);

  // Calculate full resolution datetime
  const fullResolutionDate = useMemo(() => {
    if (!resolutionDate) return undefined;
    return createDateTimeFromLocal(resolutionDate, selectedHour, selectedMinute);
  }, [resolutionDate, selectedHour, selectedMinute]);

  // Validate minimum 1 hour in future
  const isValidTime = fullResolutionDate ? isValidFutureTimeOneHour(fullResolutionDate) : true;

  // Fetch tweet data when URL changes
  useEffect(() => {
    const fetchData = async () => {
      if (!tweetUrl) {
        setTweetData(null);
        setFetchError(null);
        return;
      }

      if (!isValidTweetUrl(tweetUrl)) {
        setTweetData(null);
        setFetchError('Invalid URL format');
        return;
      }

      setIsFetching(true);
      setFetchError(null);

      try {
        const result = await fetchTweetMetrics(tweetUrl);
        if (result.success && result.data) {
          setTweetData(result.data);
          setFetchError(null);
        } else {
          setTweetData(null);
          setFetchError(result.error || 'Failed to fetch tweet');
        }
      } catch (error) {
        setTweetData(null);
        setFetchError('Network error');
        toast({
          title: "Failed to fetch tweet",
          description: "Could not retrieve tweet data",
          variant: "destructive",
        });
      } finally {
        setIsFetching(false);
      }
    };

    const debounce = setTimeout(fetchData, 500);
    return () => clearTimeout(debounce);
  }, [tweetUrl]);

  // Get current metric value from tweet data (for display only)
  const currentMetricValue = useMemo(() => {
    if (!tweetData) return 0;
    return tweetData[selectedMetric];
  }, [tweetData, selectedMetric]);

  // Auto-generate feed title
  const autoGeneratedTitle = useMemo(() => {
    if (!tweetData || !fullResolutionDate) return '';
    const dateLabel = formatDateTimeForTitle(fullResolutionDate);
    const metricName = getMetricLabel(selectedMetric);
    return `@${tweetData.username} ${metricName} [${dateLabel}]`;
  }, [tweetData, selectedMetric, fullResolutionDate]);

  const handleCreate = () => {
    if (!tweetData || !fullResolutionDate) return;
    onCreateFeed({
      tweetUrl,
      metric: selectedMetric,
      resolutionDate: fullResolutionDate,
      title: autoGeneratedTitle,
      tweetData,
    });
  };

  const canCreate = connected && tweetData && fullResolutionDate && isValidTime;

  return (
    <ModuleCard
      iconImage={xIcon}
      title="Social Markets"
      description="Create oracles based on X/Twitter engagement metrics"
      index={5}
    >
      <div className="space-y-4 flex-1 flex flex-col">
        {/* Tweet URL Input */}
        <div className="space-y-2">
          <Label className="text-sm font-medium text-foreground">Tweet URL</Label>
          <Input
            placeholder="https://x.com/username/status/123..."
            value={tweetUrl}
            onChange={(e) => setTweetUrl(e.target.value)}
            className="bg-background border-border font-mono text-sm"
          />
          
          {/* Loading Skeleton */}
          {isFetching && (
            <div className="p-3 rounded-lg border border-border bg-card space-y-3">
              <div className="flex items-start gap-3">
                <Skeleton className="w-10 h-10 rounded-full" />
                <div className="flex-1 space-y-2">
                  <Skeleton className="h-4 w-32" />
                  <Skeleton className="h-3 w-24" />
                </div>
              </div>
              <Skeleton className="h-12 w-full" />
              <div className="flex gap-4">
                <Skeleton className="h-4 w-16" />
                <Skeleton className="h-4 w-16" />
                <Skeleton className="h-4 w-16" />
              </div>
            </div>
          )}
          
          {/* Tweet Preview - Trading Terminal Style */}
          {tweetData && !isFetching && (
            <div className="p-3 rounded-lg border border-primary/30 bg-card relative overflow-hidden">
              {/* Live indicator */}
              <div className="absolute top-2 right-2 flex items-center gap-1.5">
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
                </span>
                <span className="text-[10px] font-bold text-green-500 uppercase tracking-wider">Live</span>
              </div>
              
              {/* User info */}
              <div className="flex items-start gap-3 mb-2">
                <img 
                  src={tweetData.avatarUrl} 
                  alt={tweetData.username}
                  className="w-10 h-10 rounded-full border-2 border-primary/20"
                  onError={(e) => { 
                    e.currentTarget.src = `https://api.dicebear.com/7.x/identicon/svg?seed=${tweetData.username}`;
                  }}
                />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-1.5">
                    <span className="font-semibold text-foreground">{tweetData.displayName}</span>
                    {tweetData.isVerified && (
                      <CheckCircle className="h-4 w-4 text-primary fill-primary" />
                    )}
                  </div>
                  <span className="text-sm text-muted-foreground">@{tweetData.username}</span>
                </div>
                <a
                  href={tweetUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-muted-foreground hover:text-primary transition-colors p-1"
                >
                  <ExternalLink className="h-4 w-4" />
                </a>
              </div>
              
              {/* Tweet text */}
              <p className="text-sm text-muted-foreground line-clamp-2 mb-3">{tweetData.tweetText}</p>
              
              {/* Metrics - Terminal Style */}
              <div className="grid grid-cols-2 gap-2 p-2 rounded-md bg-secondary/50 border border-border">
                <div className={cn(
                  "text-center p-1.5 rounded transition-all",
                  selectedMetric === 'likes' && "bg-primary/20 ring-1 ring-primary/50"
                )}>
                  <Heart className={cn(
                    "h-4 w-4 mx-auto mb-1",
                    selectedMetric === 'likes' ? "text-primary" : "text-muted-foreground"
                  )} />
                  <div className={cn(
                    "text-sm font-mono font-bold",
                    selectedMetric === 'likes' ? "text-primary" : "text-foreground"
                  )}>
                    {formatMetricNumber(tweetData.likes)}
                  </div>
                  <div className="text-[10px] text-muted-foreground uppercase">Likes</div>
                </div>
                <div className={cn(
                  "text-center p-1.5 rounded transition-all",
                  selectedMetric === 'retweets' && "bg-primary/20 ring-1 ring-primary/50"
                )}>
                  <Repeat className={cn(
                    "h-4 w-4 mx-auto mb-1",
                    selectedMetric === 'retweets' ? "text-primary" : "text-muted-foreground"
                  )} />
                  <div className={cn(
                    "text-sm font-mono font-bold",
                    selectedMetric === 'retweets' ? "text-primary" : "text-foreground"
                  )}>
                    {formatMetricNumber(tweetData.retweets)}
                  </div>
                  <div className="text-[10px] text-muted-foreground uppercase">Retweets</div>
                </div>
              </div>
            </div>
          )}
          
          {/* Error State */}
          {fetchError && !isFetching && tweetUrl && (
            <div className="flex items-center gap-2 p-2 bg-destructive/10 border border-destructive/20 rounded-md">
              <XCircle className="h-4 w-4 text-destructive shrink-0" />
              <span className="text-sm text-destructive">{fetchError}</span>
            </div>
          )}
        </div>

        {/* Metric Selector */}
        <div className="space-y-2">
          <Label className="text-sm font-medium text-foreground">Metric to Track</Label>
          <Select value={selectedMetric} onValueChange={(v) => setSelectedMetric(v as SocialMetric)}>
            <SelectTrigger className="bg-background border-border">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="bg-popover border-border">
              {METRIC_OPTIONS.map((option) => {
                const Icon = option.icon;
                return (
                  <SelectItem key={option.value} value={option.value}>
                    <div className="flex items-center gap-2">
                      <Icon className="h-4 w-4 text-muted-foreground" />
                      <span>{option.label}</span>
                    </div>
                  </SelectItem>
                );
              })}
            </SelectContent>
          </Select>
        </div>

        {/* Resolution Date & Time */}
        <div className="space-y-2">
          <Label className="text-sm font-medium text-foreground">
            Resolution Date <span className="text-muted-foreground text-xs">({tzAbbr})</span>
          </Label>
          <div className="flex flex-wrap gap-2">
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className={cn(
                    "flex-1 min-w-[140px] justify-start text-left font-normal bg-background border-border",
                    !resolutionDate && "text-muted-foreground"
                  )}
                >
                  <CalendarIcon className="mr-2 h-4 w-4 shrink-0" />
                  <span className="truncate">{resolutionDate ? format(resolutionDate, "MMM d, yyyy") : "Select date"}</span>
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0 bg-popover border-border z-50" align="start" collisionPadding={16}>
                <Calendar
                  mode="single"
                  selected={resolutionDate}
                  onSelect={setResolutionDate}
                  disabled={(date) => date < new Date()}
                  initialFocus
                  className="p-3 pointer-events-auto"
                />
              </PopoverContent>
            </Popover>
            
            {/* Time Selection */}
            <div className="flex items-center gap-1">
              <Clock className="h-4 w-4 text-muted-foreground" />
              <Input
                type="text"
                inputMode="numeric"
                maxLength={2}
                value={selectedHour}
                onChange={(e) => {
                  const val = e.target.value.replace(/\D/g, '').slice(0, 2);
                  setSelectedHour(val);
                }}
                onBlur={(e) => {
                  let val = parseInt(e.target.value) || 0;
                  val = Math.min(23, Math.max(0, val));
                  setSelectedHour(val.toString().padStart(2, '0'));
                }}
                className="w-14 bg-background border-border text-center font-mono"
                placeholder="HH"
              />
              <span className="text-muted-foreground font-medium">:</span>
              <Input
                type="text"
                inputMode="numeric"
                maxLength={2}
                value={selectedMinute}
                onChange={(e) => {
                  const val = e.target.value.replace(/\D/g, '').slice(0, 2);
                  setSelectedMinute(val);
                }}
                onBlur={(e) => {
                  let val = parseInt(e.target.value) || 0;
                  val = Math.min(59, Math.max(0, val));
                  setSelectedMinute(val.toString().padStart(2, '0'));
                }}
                className="w-14 bg-background border-border text-center font-mono"
                placeholder="MM"
              />
            </div>
          </div>
          
          {/* Time Validation Error */}
          {fullResolutionDate && !isValidTime && (
            <p className="text-xs text-destructive flex items-center gap-1">
              <XCircle className="h-3 w-3" />
              Minimum duration is 1 hour from now
            </p>
          )}
        </div>

        {/* Auto-generated Title Preview */}
        {autoGeneratedTitle && (
          <div className="space-y-2">
            <Label className="text-sm font-medium text-muted-foreground">Market Title (auto)</Label>
            <div className="px-3 py-2 bg-muted/50 rounded-md border border-border/50 min-h-[40px] flex items-center">
              <span className="text-sm text-foreground font-mono line-clamp-2">{autoGeneratedTitle}</span>
            </div>
          </div>
        )}
        
        {/* Spacer */}
        <div className="flex-1" />

        <div className="flex items-center justify-between pt-2">
          <FeeDisplay />
          <Button
            variant={deploymentState === 'success' ? 'default' : 'gold'}
            size="sm"
            onClick={handleCreate}
            disabled={!canCreate || isLoading}
            className={deploymentState === 'success' ? 'bg-green-500 hover:bg-green-600' : ''}
          >
            {getButtonText ? getButtonText('Create Market') : (isLoading ? 'Creating...' : 'Create Market')}
          </Button>
        </div>
      </div>
    </ModuleCard>
  );
};
