import { FC, useState, useEffect, useMemo } from 'react';
import { Check, ChevronsUpDown, Search, AlertCircle, Loader2 } from 'lucide-react';
import sportsIcon from '@/assets/sports-icon.png';
import { ModuleCard } from './ModuleCard';
import { Button } from '@/components/ui/button';
import { FeeDisplay } from './FeeDisplay';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Command, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem } from '@/components/ui/command';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useWallet } from '@solana/wallet-adapter-react';
import { supabase } from '@/integrations/supabase/client';
import { format, addHours } from 'date-fns';

// Types
type SportType = 'basketball' | 'hockey' | 'soccer' | 'tennis';

interface SportsMatch {
  id: string;
  sport: string;
  sportKey: string;
  homeTeam: string;
  awayTeam: string;
  commenceTime: string;
  league: string;
}

// Sport configuration
const SPORTS_CONFIG: Record<SportType, { label: string; icon: string; color: string; bufferHours: number }> = {
  basketball: { label: 'Basketball', icon: '🏀', color: 'bg-orange-500/20 text-orange-400 border-orange-500/30', bufferHours: 3 },
  hockey: { label: 'Hockey', icon: '🏒', color: 'bg-blue-500/20 text-blue-400 border-blue-500/30', bufferHours: 3 },
  soccer: { label: 'Soccer', icon: '⚽', color: 'bg-green-500/20 text-green-400 border-green-500/30', bufferHours: 2.5 },
  tennis: { label: 'Tennis', icon: '🎾', color: 'bg-purple-500/20 text-purple-400 border-purple-500/30', bufferHours: 4 },
};

interface SportsModuleProps {
  onCreateFeed: (config: {
    sport: string;
    sportKey: string;
    eventId: string;
    homeTeam: string;
    awayTeam: string;
    league: string;
    resolutionDate: Date;
    title: string;
    commenceTime: string;
  }) => void;
  isLoading: boolean;
  deploymentState?: string;
  getButtonText: (defaultText: string) => string;
}

export const SportsModule: FC<SportsModuleProps> = ({
  onCreateFeed,
  isLoading,
  deploymentState,
  getButtonText,
}) => {
  const { connected } = useWallet();
  const [selectedSport, setSelectedSport] = useState<SportType>('basketball');
  const [selectedMatch, setSelectedMatch] = useState<SportsMatch | null>(null);
  const [matches, setMatches] = useState<SportsMatch[]>([]);
  const [isFetching, setIsFetching] = useState(false);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [matchSelectorOpen, setMatchSelectorOpen] = useState(false);

  // Fetch matches when sport changes
  useEffect(() => {
    const fetchMatches = async () => {
      setIsFetching(true);
      setFetchError(null);
      setSelectedMatch(null);

      try {
        const response = await fetch(
          `https://zryeulucckdgaiboxntn.supabase.co/functions/v1/sports-matches?sport=${selectedSport}`,
          {
            headers: {
              'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
              'Content-Type': 'application/json',
            },
          }
        );
        
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}`);
        }
        
        const data = await response.json();
        
        if (data.error) throw new Error(data.error);

        

        setMatches(data?.matches || []);
      } catch (err: any) {
        console.error('Error fetching sports matches:', err);
        setFetchError(err.message || 'Failed to fetch matches');
        setMatches([]);
      } finally {
        setIsFetching(false);
      }
    };

    fetchMatches();
  }, [selectedSport]);

  // Filter matches by search query
  const filteredMatches = useMemo(() => {
    if (!searchQuery.trim()) return matches;
    const query = searchQuery.toLowerCase();
    return matches.filter(
      (m) =>
        m.homeTeam.toLowerCase().includes(query) ||
        m.awayTeam.toLowerCase().includes(query) ||
        m.league.toLowerCase().includes(query)
    );
  }, [matches, searchQuery]);

  // Calculate resolution date based on selected match
  const resolutionDate = useMemo(() => {
    if (!selectedMatch) return null;
    const config = SPORTS_CONFIG[selectedSport];
    const matchStart = new Date(selectedMatch.commenceTime);
    return addHours(matchStart, config.bufferHours);
  }, [selectedMatch, selectedSport]);

  // Generate title
  const autoGeneratedTitle = useMemo(() => {
    if (!selectedMatch || !resolutionDate) return '';
    return `${selectedMatch.homeTeam} vs ${selectedMatch.awayTeam} Winner @ ${format(resolutionDate, 'dd MMM HH:mm')} UTC`;
  }, [selectedMatch, resolutionDate]);

  const handleCreate = () => {
    if (!selectedMatch || !resolutionDate) return;

    onCreateFeed({
      sport: selectedSport,
      sportKey: selectedMatch.sportKey,
      eventId: selectedMatch.id,
      homeTeam: selectedMatch.homeTeam,
      awayTeam: selectedMatch.awayTeam,
      league: selectedMatch.league,
      resolutionDate,
      title: autoGeneratedTitle,
      commenceTime: selectedMatch.commenceTime,
    });
  };

  const sportConfig = SPORTS_CONFIG[selectedSport];

  return (
    <ModuleCard
      iconImage={sportsIcon}
      title="Sports"
      description="Traditional sports data feeds"
      index={4}
    >
      <div className="space-y-4 flex-1 flex flex-col">
        {/* Sport Selector */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Sport</label>
          <Select value={selectedSport} onValueChange={(v) => setSelectedSport(v as SportType)}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {Object.entries(SPORTS_CONFIG).map(([key, config]) => (
                <SelectItem key={key} value={key}>
                  <span className="flex items-center gap-2">
                    <span>{config.icon}</span>
                    <span>{config.label}</span>
                  </span>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Match Selector */}
        <div className="space-y-1.5">
          <label className="text-xs text-muted-foreground">Match</label>
          <Popover open={matchSelectorOpen} onOpenChange={setMatchSelectorOpen}>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                role="combobox"
                className="w-full justify-between h-auto min-h-10 py-2"
                disabled={isFetching}
              >
                {isFetching ? (
                  <span className="flex items-center gap-2 text-muted-foreground">
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Loading matches...
                  </span>
                ) : selectedMatch ? (
                  <div className="flex flex-col items-start gap-1 text-left">
                    <span className="font-medium text-sm">
                      {selectedMatch.homeTeam} vs {selectedMatch.awayTeam}
                    </span>
                    <span className="text-xs text-muted-foreground">
                      {selectedMatch.league} • {format(new Date(selectedMatch.commenceTime), 'dd MMM HH:mm')} UTC
                    </span>
                  </div>
                ) : (
                  <span className="text-muted-foreground">Select a match...</span>
                )}
                <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-[var(--radix-popover-trigger-width)] p-0" align="start">
              <Command shouldFilter={false}>
                <div className="flex items-center border-b px-3">
                  <Search className="mr-2 h-4 w-4 shrink-0 opacity-50" />
                  <input
                    placeholder="Search matches..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="flex h-10 w-full rounded-md bg-transparent py-3 text-sm outline-none placeholder:text-muted-foreground"
                  />
                </div>
                <CommandList className="max-h-[300px]">
                  {fetchError ? (
                    <div className="p-4 text-center text-sm text-destructive flex items-center justify-center gap-2">
                      <AlertCircle className="h-4 w-4" />
                      {fetchError}
                    </div>
                  ) : filteredMatches.length === 0 ? (
                    <CommandEmpty>No matches found</CommandEmpty>
                  ) : (
                    <CommandGroup>
                      {filteredMatches.map((match) => (
                        <CommandItem
                          key={match.id}
                          value={match.id}
                          onSelect={() => {
                            setSelectedMatch(match);
                            setMatchSelectorOpen(false);
                            setSearchQuery('');
                          }}
                          className="flex flex-col items-start gap-1 py-3 cursor-pointer"
                        >
                          <div className="flex items-center gap-2 w-full">
                            {selectedMatch?.id === match.id && (
                              <Check className="h-4 w-4 text-primary flex-shrink-0" />
                            )}
                            <span className="font-medium text-sm">
                              {match.homeTeam} vs {match.awayTeam}
                            </span>
                          </div>
                          <div className="flex items-center gap-2 pl-6">
                            <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded border ${sportConfig.color}`}>
                              {match.league}
                            </span>
                            <span className="text-xs text-muted-foreground">
                              {format(new Date(match.commenceTime), 'dd MMM HH:mm')} UTC
                            </span>
                          </div>
                        </CommandItem>
                      ))}
                    </CommandGroup>
                  )}
                </CommandList>
              </Command>
            </PopoverContent>
          </Popover>
        </div>

        {/* Resolution Date (read-only) */}
        {selectedMatch && resolutionDate && (
          <div className="space-y-1.5">
            <label className="text-xs text-muted-foreground">Est. Resolution Date (UTC)</label>
            <div className="p-2.5 rounded-md border bg-muted/50 text-sm font-mono">
              {format(resolutionDate, 'dd MMM yyyy HH:mm')} UTC
            </div>
          </div>
        )}

        {/* Spacer */}
        <div className="flex-1" />

        {/* Footer */}
        <div className="flex items-center justify-between pt-2">
          <FeeDisplay />
          <Button
            variant="gold"
            size="sm"
            onClick={handleCreate}
            disabled={!connected || !selectedMatch || isLoading}
          >
            {getButtonText('Create Oracle')}
          </Button>
        </div>
      </div>
    </ModuleCard>
  );
};
