import { FC, useState, useMemo, useEffect } from 'react';
import { CalendarIcon, Loader2, CheckCircle, XCircle, Check, ChevronsUpDown, Clock } from 'lucide-react';
import weatherIcon from '@/assets/weather-icon.png';
import { ModuleCard } from './ModuleCard';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from '@/components/ui/command';
import { FeeDisplay } from './FeeDisplay';
import { useWallet } from '@solana/wallet-adapter-react';
import { cn } from '@/lib/utils';
import { format, addDays, startOfDay } from 'date-fns';
import { fetchWeatherDataDirect, WeatherData } from '@/utils/apiService';
import { toast } from '@/hooks/use-toast';
import { CAPITALS_LIST, Capital } from '@/data/capitalsList';
import { DeploymentState } from '@/hooks/useCreateFeed';
import { 
  calculateResolutionDate, 
  formatSettlementPreview,
  formatTargetDateForTitle,
  formatDateForAPI
} from '@/utils/weatherTimeUtils';

type WeatherMetric = 'temp_max' | 'temp_min' | 'precipitation';

const WEATHER_METRICS = [
  { value: 'temp_max', label: 'Max Temperature (°C)' },
  { value: 'temp_min', label: 'Min Temperature (°C)' },
] as const;

interface WeatherModuleProps {
  onCreateFeed: (config: { 
    location: string; 
    lat: number;
    lon: number;
    timezone: string;
    metric: WeatherMetric;
    date: string; // YYYY-MM-DD format for target date
    resolutionDate: Date; // UTC resolution time
    title: string;
  }) => void;
  isLoading?: boolean;
  deploymentState?: DeploymentState;
  getButtonText?: (defaultText?: string) => string;
}

export const WeatherModule: FC<WeatherModuleProps> = ({ onCreateFeed, isLoading, deploymentState, getButtonText }) => {
  const { connected } = useWallet();
  const [selectedCity, setSelectedCity] = useState<Capital | null>(null);
  const [open, setOpen] = useState(false);
  const [metric, setMetric] = useState<WeatherMetric>('temp_max');
  
  // Initialize with tomorrow's date (minimum selectable)
  const tomorrow = addDays(startOfDay(new Date()), 1);
  const [targetDate, setTargetDate] = useState<Date | undefined>(tomorrow);
  
  // Live preview state
  const [weatherData, setWeatherData] = useState<WeatherData | null>(null);
  const [isFetching, setIsFetching] = useState(false);
  const [fetchError, setFetchError] = useState(false);

  // Fetch weather data when city changes
  useEffect(() => {
    const fetchData = async () => {
      if (!selectedCity) {
        setWeatherData(null);
        setFetchError(false);
        return;
      }

      setIsFetching(true);
      setFetchError(false);

      try {
        const data = await fetchWeatherDataDirect(selectedCity.lat, selectedCity.lon, selectedCity.name);
        if (data) {
          setWeatherData(data);
          setFetchError(false);
        } else {
          setWeatherData(null);
          setFetchError(true);
        }
      } catch (error) {
        setWeatherData(null);
        setFetchError(true);
        toast({
          title: "Failed to fetch data",
          description: "Could not retrieve weather data from Open-Meteo",
          variant: "destructive",
        });
      } finally {
        setIsFetching(false);
      }
    };

    fetchData();
  }, [selectedCity]);

  // Settlement preview text
  const settlementPreview = useMemo(() => {
    if (!selectedCity || !targetDate) return '';
    return formatSettlementPreview(targetDate, selectedCity.timezone, selectedCity.name);
  }, [selectedCity, targetDate]);

  // Auto-generate feed title
  const autoGeneratedTitle = useMemo(() => {
    if (!selectedCity || !targetDate) return '';
    const metricShort = metric === 'temp_max' ? 'Max Temp' : metric === 'temp_min' ? 'Min Temp' : 'Precip';
    const dateLabel = formatTargetDateForTitle(targetDate);
    return `${selectedCity.name} ${metricShort} [${dateLabel}]`;
  }, [selectedCity, metric, targetDate]);

  const handleCreate = () => {
    if (!selectedCity || !targetDate) return;
    
    const resolutionDate = calculateResolutionDate(targetDate, selectedCity.timezone);
    
    onCreateFeed({
      location: selectedCity.name,
      lat: selectedCity.lat,
      lon: selectedCity.lon,
      timezone: selectedCity.timezone,
      metric,
      date: formatDateForAPI(targetDate),
      resolutionDate,
      title: autoGeneratedTitle,
    });
  };

  const canCreate = connected && selectedCity && targetDate && weatherData;

  // Disable dates before tomorrow
  const disabledDays = (date: Date) => {
    const today = startOfDay(new Date());
    return date <= today;
  };

  return (
    <ModuleCard
      iconImage={weatherIcon}
      title="Weather"
      description="Hyper-local meteorological feeds for on-chain settlements"
      index={2}
    >
      <div className="space-y-4 flex-1 flex flex-col">
        {/* City Selection Combobox */}
        <div className="space-y-2">
          <Label className="text-sm font-medium text-foreground">Location</Label>
          <Popover open={open} onOpenChange={setOpen}>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                role="combobox"
                aria-expanded={open}
                className="w-full justify-between bg-background border-border max-w-full overflow-hidden"
              >
                {selectedCity ? (
                  <span className="truncate min-w-0">
                    <span className="font-medium">{selectedCity.name}</span>
                    <span className="text-muted-foreground ml-1">({selectedCity.country})</span>
                  </span>
                ) : (
                  <span className="text-muted-foreground truncate">Search city...</span>
                )}
                <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-[300px] p-0 bg-popover border-border z-50" align="start">
              <Command>
                <CommandInput placeholder="Search city..." />
                <CommandList>
                  <CommandEmpty>No city found.</CommandEmpty>
                  <CommandGroup className="max-h-[200px] overflow-y-auto">
                    {CAPITALS_LIST.map((city) => (
                      <CommandItem
                        key={city.name}
                        value={`${city.name} ${city.country}`}
                        onSelect={() => {
                          setSelectedCity(city);
                          setOpen(false);
                        }}
                        className="flex items-center gap-2 cursor-pointer"
                      >
                        <span className="font-medium">{city.name}</span>
                        <span className="text-muted-foreground">({city.country})</span>
                        <Check
                          className={cn(
                            "ml-auto h-4 w-4",
                            selectedCity?.name === city.name ? "opacity-100" : "opacity-0"
                          )}
                        />
                      </CommandItem>
                    ))}
                  </CommandGroup>
                </CommandList>
              </Command>
            </PopoverContent>
          </Popover>
          
          {/* Live Preview */}
          {isFetching && (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="h-3 w-3 animate-spin" />
              <span>Fetching weather...</span>
            </div>
          )}
          
          {weatherData && !isFetching && selectedCity && (
            <div className="flex items-start gap-2 p-2 bg-green-500/10 border border-green-500/20 rounded-md">
              <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
              <div className="text-sm">
                <span className="text-green-600 font-medium">✓ {weatherData.location}</span>
                <span className="text-muted-foreground"> (Lat: {weatherData.lat.toFixed(2)}, Long: {weatherData.lon.toFixed(2)})</span>
                <span className="text-muted-foreground"> | </span>
                <span className="text-foreground">Temp: {weatherData.temperature}°C</span>
              </div>
            </div>
          )}
          
          {fetchError && !isFetching && selectedCity && (
            <div className="flex items-center gap-2 p-2 bg-destructive/10 border border-destructive/20 rounded-md">
              <XCircle className="h-4 w-4 text-destructive shrink-0" />
              <span className="text-sm text-destructive">Failed to fetch weather data</span>
            </div>
          )}
        </div>

        {/* Metric */}
        <div className="space-y-2">
          <Label className="text-sm font-medium text-foreground">Metric</Label>
          <Select value={metric} onValueChange={(v) => setMetric(v as WeatherMetric)}>
            <SelectTrigger className="bg-background border-border">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="bg-popover border-border z-50">
              {WEATHER_METRICS.map((m) => (
                <SelectItem key={m.value} value={m.value}>
                  {m.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Target Date (Date only, no time selection) */}
        <div className="space-y-2">
          <Label className="text-sm font-medium text-foreground">
            Target Date <span className="text-muted-foreground text-xs">(weather data for this day)</span>
          </Label>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                className={cn(
                  "w-full justify-start text-left font-normal bg-background border-border",
                  !targetDate && "text-muted-foreground"
                )}
              >
                <CalendarIcon className="mr-2 h-4 w-4 shrink-0" />
                <span className="truncate">{targetDate ? format(targetDate, "PPP") : "Select target date"}</span>
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0 bg-popover border-border z-50" align="start" collisionPadding={16}>
              <Calendar
                mode="single"
                selected={targetDate}
                onSelect={setTargetDate}
                disabled={disabledDays}
                initialFocus
                className="p-3 pointer-events-auto"
              />
            </PopoverContent>
          </Popover>
          
          {/* Settlement Time Preview */}
          {settlementPreview && (
            <div className="flex items-center gap-2 p-2 bg-primary/5 border border-primary/20 rounded-md">
              <Clock className="h-4 w-4 text-primary shrink-0" />
              <span className="text-sm text-muted-foreground">{settlementPreview}</span>
            </div>
          )}
        </div>

        {/* Auto-generated Feed Title Preview */}
        {autoGeneratedTitle && (
          <div className="space-y-2">
            <Label className="text-sm font-medium text-muted-foreground">Feed Title (auto)</Label>
            <div className="px-3 py-2 bg-muted/50 rounded-md border border-border/50 h-10 flex items-center">
              <span className="text-sm text-foreground truncate">{autoGeneratedTitle}</span>
            </div>
          </div>
        )}
        
        {/* Spacer to push button to bottom */}
        <div className="flex-1" />

        <div className="flex items-center justify-between pt-2">
          <FeeDisplay />
          <Button
            variant={deploymentState === 'success' ? 'default' : 'gold'}
            size="sm"
            onClick={handleCreate}
            disabled={!canCreate || isLoading}
            className={deploymentState === 'success' ? 'bg-green-500 hover:bg-green-600' : ''}
          >
            {getButtonText ? getButtonText('Create Oracle') : (isLoading ? 'Creating...' : 'Create Oracle')}
          </Button>
        </div>
      </div>
    </ModuleCard>
  );
};
